#!/usr/bin/env python3
"""Index and promote generated screenshots into dataset candidate manifests.

Usage:
    # Show summary of a capture batch
    python3 ml/scripts/index_generated_screenshots.py \\
        --input ~/Datasets/axiom-mobile/generated_screenshots

    # Promote reviewed captures to a staging manifest
    python3 ml/scripts/index_generated_screenshots.py \\
        --input ~/Datasets/axiom-mobile/generated_screenshots \\
        --promote --start-id 53

    # Preview what would be written (dry run)
    python3 ml/scripts/index_generated_screenshots.py \\
        --input ~/Datasets/axiom-mobile/generated_screenshots \\
        --promote --start-id 53 --dry-run

Reads:
    {input}/capture_index.jsonl — generated by capture_screenshots.sh

Writes (--promote):
    data/manifests/generated_candidates.jsonl — staging manifest for review
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent.parent


def load_capture_index(input_dir: Path) -> list[dict[str, Any]]:
    """Load the capture index JSONL from a batch directory."""
    index_path = input_dir / "capture_index.jsonl"
    if not index_path.exists():
        print(f"ERROR: No capture_index.jsonl found in {input_dir}")
        sys.exit(1)

    entries: list[dict[str, Any]] = []
    with open(index_path) as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue
            try:
                entries.append(json.loads(line))
            except json.JSONDecodeError as e:
                print(f"  [warn] Line {line_num}: invalid JSON — {e}")
    return entries


def summarize(entries: list[dict[str, Any]]) -> None:
    """Print a summary of the capture index."""
    print(f"\nCapture Index Summary")
    print(f"{'=' * 50}")
    print(f"Total entries: {len(entries)}")

    if not entries:
        return

    # Screen families
    families = Counter(e.get("screen_family", "unknown") for e in entries)
    print(f"\nScreen families:")
    for family, count in families.most_common():
        print(f"  {family}: {count}")

    # Q&A template counts
    total_qa = sum(len(e.get("qa_templates", [])) for e in entries)
    print(f"\nTotal Q&A templates: {total_qa}")
    print(f"Average Q&A per screenshot: {total_qa / len(entries):.1f}")

    # Sources
    sources = Counter(e.get("source", "unknown") for e in entries)
    print(f"\nSources:")
    for source, count in sources.most_common():
        print(f"  {source}: {count}")

    # Batch IDs
    batches = Counter(e.get("batch_id", "unknown") for e in entries)
    print(f"\nBatches:")
    for batch, count in batches.most_common():
        print(f"  {batch}: {count}")

    # File sizes
    sizes = [e.get("file_size_bytes", 0) for e in entries]
    if sizes:
        avg_kb = sum(sizes) / len(sizes) / 1024
        print(f"\nAverage file size: {avg_kb:.0f} KB")

    print()


def promote_to_candidates(
    entries: list[dict[str, Any]],
    start_id: int,
    dry_run: bool = False,
) -> Path:
    """Expand Q&A templates into dataset-compatible candidate entries.

    Each capture entry with N Q&A templates produces N candidate rows,
    each with a unique example ID and the same image filename.
    """
    candidates: list[dict[str, str | int]] = []
    current_id = start_id

    for entry in entries:
        image_filename = entry.get("image_filename", "")
        qa_templates = entry.get("qa_templates", [])
        notes = entry.get("notes", "")
        scenario_id = entry.get("scenario_id", "")

        if not qa_templates:
            # Create a placeholder entry for screenshots without templates
            candidates.append({
                "id": f"ex_{current_id:03d}",
                "image_filename": image_filename,
                "question": "[NEEDS LABELING]",
                "answer": "[NEEDS LABELING]",
                "difficulty": 1,
                "notes": f"{notes} (auto-captured: {scenario_id})",
                "_status": "needs_labeling",
                "_source": "simulator_generated",
                "_scenario_id": scenario_id,
            })
            current_id += 1
            continue

        for qa in qa_templates:
            question = qa.get("question", "[NEEDS LABELING]")
            answer_hint = qa.get("answer_hint", "[NEEDS LABELING]")
            difficulty = qa.get("difficulty", 1)

            candidates.append({
                "id": f"ex_{current_id:03d}",
                "image_filename": image_filename,
                "question": question,
                "answer": answer_hint,
                "difficulty": difficulty,
                "notes": f"{notes} (auto-captured: {scenario_id})",
                "_status": "needs_review",
                "_source": "simulator_generated",
                "_scenario_id": scenario_id,
            })
            current_id += 1

    output_path = _PROJECT_ROOT / "data" / "manifests" / "generated_candidates.jsonl"

    print(f"\nCandidate generation:")
    print(f"  Screenshots: {len(entries)}")
    print(f"  Candidate entries: {len(candidates)}")
    print(f"  ID range: ex_{start_id:03d} — ex_{current_id - 1:03d}")
    print(f"  Output: {output_path.relative_to(_PROJECT_ROOT)}")

    if dry_run:
        print("\n  [dry-run] No files written.")
        print("\n  Sample entries:")
        for c in candidates[:3]:
            print(f"    {json.dumps(c)}")
        return output_path

    # Write staging manifest
    with open(output_path, "w") as f:
        for candidate in candidates:
            f.write(json.dumps(candidate) + "\n")

    print(f"  [ok] Wrote {len(candidates)} candidates")

    # Validation summary
    needs_labeling = sum(1 for c in candidates if c.get("_status") == "needs_labeling")
    needs_review = sum(1 for c in candidates if c.get("_status") == "needs_review")
    print(f"\n  Status breakdown:")
    print(f"    needs_review:   {needs_review}")
    print(f"    needs_labeling: {needs_labeling}")

    print(f"\n  Next steps:")
    print(f"    1. Review screenshots in the capture directory")
    print(f"    2. Edit {output_path.name}: fix answer_hint values to exact answers")
    print(f"    3. Remove _ prefixed fields and move approved rows to pool/val/test")
    print(f"    4. Run: python3 ml/scripts/inspect_dataset.py")
    print(f"    5. Run: python3 ml/scripts/annotation_qc.py")

    return output_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Index and promote generated screenshots"
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path.home() / "Datasets" / "axiom-mobile" / "generated_screenshots",
        help="Directory containing capture_index.jsonl",
    )
    parser.add_argument(
        "--promote",
        action="store_true",
        help="Generate a staging manifest (generated_candidates.jsonl)",
    )
    parser.add_argument(
        "--start-id",
        type=int,
        default=53,
        help="Starting example ID for candidates (default: 53, after current 52)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview without writing files",
    )
    args = parser.parse_args()

    entries = load_capture_index(args.input)
    summarize(entries)

    if args.promote:
        promote_to_candidates(
            entries,
            start_id=args.start_id,
            dry_run=args.dry_run,
        )


if __name__ == "__main__":
    main()
